name: Verify Pull Request
on:
  workflow_dispatch: # manual trigger
  pull_request:
    types: [ opened, reopened, ready_for_review, synchronize ]
    branches: [ "development", "master" ]
jobs:
  verify:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Flutter SDK
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: flutter-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            flutter-${{ runner.os }}-
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
      - name: Setup Melos
        run: dart pub global activate melos
      - name: Melos Bootstrap
        run:  melos bootstrap
      - name: Install dependencies
        run: melos get
      - name: Analyze
        run: melos analyze
      - name: Run tests
        run:  melos unittest
      - name: Check Publish Warnings
        run: melos exec -c 1 --no-private --ignore="*example*" -- flutter pub publish --dry-run