name: Verify Pull Request
on:
  workflow_dispatch: # manual trigger
  pull_request:
    types: [ opened, reopened, ready_for_review, synchronize ]
    branches: [ "development", "master" ]
jobs:
  verify:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          cache: true
          cache-key: "flutter-${{ runner.os }}-${{ github.event.inputs.channel }}-${{ github.event.inputs.version }}-${{ runner.architecture }}-${{ hashFiles('**') }}"
          cache-path: "${{ runner.tool_cache }}/flutter/${{ github.event.inputs.channel }}-${{ github.event.inputs.version }}-${{ runner.architecture }}"
          pub-cache-key: "flutter-pub-${{ runner.os }}-${{ github.event.inputs.channel }}-${{ github.event.inputs.version }}-${{ runner.architecture }}-${{ hashFiles('**') }}"
          pub-cache-path: "${{ runner.tool_cache }}/flutter/${{ github.event.inputs.channel }}-${{ github.event.inputs.version }}-${{ runner.architecture }}"
      - name: Setup Melos
        run: dart pub global activate melos
      - name: Melos Bootstrap
        run:  melos bootstrap
      - name: Install dependencies
        run: melos get
      - name: Analyze
        run: melos analyze
      - name: Run tests
        run:  melos unittest
      - name: Check Publish Warnings
        run: melos exec -c 1 --no-private --ignore="*example*" -- flutter pub publish --dry-run